name: Java CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '16']
    steps:
      - uses: actions/checkout@v1
      - name: 'Download latest JDK 17'
        run: wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: jdk-17_linux-x64_bin.tar.gz
      - run: mvn -v
      - run: mvn --batch-mode --no-transfer-progress verify
      - run: java -cp target/my-app-1.0-SNAPSHOT.jar com.github.fwilhe.Main
      - run: mvn --batch-mode --no-transfer-progress exec:java -Dexec.mainClass="com.github.fwilhe.Main"
