name: Java CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '16']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - run: mvn -v
      - run: mvn --batch-mode --no-transfer-progress verify
      - run: java -cp target/my-app-1.0-SNAPSHOT.jar com.github.fwilhe.Main
      - run: mvn --batch-mode --no-transfer-progress exec:java -Dexec.mainClass="com.github.fwilhe.Main"
